colors_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts

  root 'posts#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get    'color_all'   => 'colors#index'
  get    'color_new'   => 'colors#new'
  post   'color_post'   => 'colors#create'
  delete 'color_del'  => 'colors#destroy'

end

# Prefix    Verb   URI Pattern               Controller#Action
# users     GET    /users(.:format)          users#index
#           POST   /users(.:format)          users#create
# new_user  GET    /users/new(.:format)      users#new
# edit_user GET    /users/:id/edit(.:format) users#edit
# user      GET    /users/:id(.:format)      users#show
#           PATCH  /users/:id(.:format)      users#update
#           PUT    /users/:id(.:format)      users#update
#           DELETE /users/:id(.:format)      users#destroy
# posts     GET    /posts(.:format)          posts#index
#           POST   /posts(.:format)          posts#create
# new_post  GET    /posts/new(.:format)      posts#new
# edit_post GET    /posts/:id/edit(.:format) posts#edit
# post      GET    /posts/:id(.:format)      posts#show
#           PATCH  /posts/:id(.:format)      posts#update
#           PUT    /posts/:id(.:format)      posts#update
#           DELETE /posts/:id(.:format)      posts#destroy
# root      GET    /                         posts#index
# login     GET    /login(.:format)          sessions#new
#           POST   /login(.:format)          sessions#create
# logout    DELETE /logout(.:format)         sessions#destroy

colors_app/app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :users
end

colors_app/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

colors_app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_and_belongs_to_many :colors 
end

colors_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

colors_app/app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def index
      if( ! session[:user].nil? )
        @current_user = User.find( session[:user]['id'] )
        @colors = @current_user.colors
      else
        @colors = colors.all
      end
  end

def create
  name = params[:color][:color_name]
  info = params[:color][:color_info]
  user_id_info = session[:user]['id']
#d7e210
  @current_user = User.find( session[:user]['id'] )
  @color=Color.create(:color_name => name, :color_info => info)
  @color.users << @current_user
  redirect_to '/'
end

# def color_params
#   params.require(:color).permit(:color_name, :color_info, :user_id)
# end


  # ------------------
end #end class

colors_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
      if( ! session[:user].nil? )
        @current_user = User.find( session[:user]['id'] )
        @posts = @current_user.posts
        @colors = @current_user.colors
      else
        redirect_to '/login'
      end
  end

def create
  title_info = params[:post][:title]
  content_info = params[:post][:content]
  user_id_info = session[:user]['id']

  @post=Post.create(:title => title_info, :content => content_info, :user_id => user_id_info)
  redirect_to '/'
end

def user_params
  params.require(:user).permit(:username, :img_url, :password_hash, :password_confirmation)
end


  # ------------------
end #end Posts class

colors_app/app/controllers/sessions_controller.rb
require 'digest/md5'
class SessionsController < ApplicationController

  def new

  end

  def create
    password = login_params[:password_hash]
    username = login_params[:username]

    user_object = User.find_by_username( username )
    password_hash = Digest::MD5.hexdigest( password )

    if (user_object == nil)
      @status = "Incorrect Username"
      redirect_to '/login'

    elsif ( user_object.password_hash == password_hash )
      @status = ""
      session[:user] = user_object
      redirect_to '/'
    else
      @status = "Incorrect Password"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user] = nil
    redirect_to '/login'
  end

  def login_params
    params.require(:session).permit(:username, :password_hash)
  end

# ------------------
end #end Sessions class

colors_app/app/controllers/users_controller.rb
require 'digest/md5'
class UsersController < ApplicationController

  def new
  end

  def create
    username = user_params[:username]
    password = user_params[:password_hash]
    password_confirmation = user_params[:password_confirmation]

    password_hash = Digest::MD5.hexdigest( password )
    password_confirmation_hash = Digest::MD5.hexdigest( password_confirmation )

    if( password_hash != password_confirmation_hash )
        redirect_to '/users/new'

    else
     @user=User.create(:username => username, :password_hash => password_confirmation_hash)
     session[:user] = @user
     redirect_to '/'
   end
 end # end create

def user_params
  params.require(:user).permit(:username, :img_url, :password_hash, :password_confirmation)
end



# --------------------
end #end Users class

colors_app/app/helpers/application_helper.rb
module ApplicationHelper
end

colors_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:600|Karma:300' rel='stylesheet' type='text/css'>
  <link rel='stylesheet' href='spectrum.css' />
  <link rel='stylesheet' href='styles.css' />
  <title>ColorsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="jscolor.js"></script>

</html>

colors_app/app/views/posts/_form.html.erb
<%= form_for(:post, url: '/posts', :method => 'post') do |f| %>
  <%= f.text_field :title, placeholder: "Title" %><br>
  <%= f.text_area :content, size: "30x10", placeholder: "Content" %><br>
  <%= f.submit "Post"%>
<%end%>

colors_app/app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

<!-- CREATE COLOR =======================================-->
  <div id="user-side">
    <div class="header">
      <%= link_to '<button type="button"  id="logout">Logout</button>'.html_safe, logout_path, :method => 'delete'%>
      <h1 id="welcome">Welcome, <%= @current_user.username %>!</h1>
    </div>

    <div class="new-color">
      <h2>Create a new color?</h2>

      <%= form_for(:color, url: color_post_path, :method => 'post') do |f| %>
      <%= f.text_field :color_info, placeholder: "click", id: "picker", class: "jscolor {required:false, position:'right', width:101, padding:0, shadow:false,
    borderWidth:0, backgroundColor:'transparent', insetColor:'#000', hash:true, uppercase:false}" %><br>
      <%= f.text_field :color_name, placeholder: "Add Color Name" %><br>
      <%= f.submit "Create"%>
      <% end %>
    </div>

<!-- ALL YOUR COLORS =======================================-->
    <div class="your-colors">
      <div>
        <h2>Your Colors</h2>
      </div>
      <% @colors.each do |item| %>
        <div class="swatch" style="background-color: <%= item.color_info %>">
          <p><%= item.color_name %></p>
        </div>
      <% end %>
    </div>
  </div>

<!-- MAKE A POST =======================================-->
  <div id="feed-side">

      <div class="header">
      </div>

      <div class="new-posts">
        <h2>Share a color?</h2>
        <%= render partial: 'form' %>
      </div>

  <!-- ALL POSTS =======================================-->
      <div class="posts-feed">

        <div>
          <h2>Your Posts</h2>
        </div>

        <% @posts.each do |item| %>
          <div class="post">
            <div id="title">Title: <%= item.title %></div>
            <div id="content"><%= item.content %></div>
          </div>
        <% end %>

      </div>

    </div>
  </body>
</html>

colors_app/app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Register</h1>
    <%= form_for(:user, url: '/users', :method => 'post') do |f| %>

        <%= f.label :username %>
        <%= f.text_field :username %><br>

        <%= f.label :password %>
        <%= f.password_field :password_hash %><br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>

      <%= f.submit "Register"%>
    <% end %>
  </body>
</html>